### ISSUE TITLE
Build fail - cofnięcie ostatnich commitów

### ISSUE THREAD

**Issue by monikachudek** [hugo4r/hugo#12]
Niestety zakomitowałam zmiany, które spowodowały stan buildu - failed. 
A próby revertu jeszcze bardziej nabałaganiły. 
Bardzo proszę o wycofanie moich commitów i przywrócenie stanu repozytorium do commita nr e5c697d.
@pbiecek, @Irbis3 , @MatKru

**Comment by MatKru** [comment]
Zrobione
