### ISSUE TITLE
Historia

### ISSUE THREAD

**Issue by woznicak** [hugo4r/hugo#13]
Każda funkcja ma wzbogacać historię poleceń. Musimy ustalić co w tej historii będzie się znajdować.
Co powinno się znaleźć w tej historii?
Funkcje `hugo_memorise*`  mają tę dodawać do tej historii dodatkowe elementy. @golawskaj, @AnnaGierlak, jak będziecie to robić?

**Comment by lgelmo** [comment]
Ja na potrzeby funkcji hugo_show_history(), przygotowalem funkcje add_to_history(). Trzeba ją umieścić jako pierwszą funkcję w ciele każdej funkcji hugo. Dodaje ona wpis o wywołaniu funkcji do zmiennej globalnej o nazwie hugo_history. A pierwsze użycie jakiejś funkcji hugo, tworzy zmienną hugo_history. (Jest już ona w repozytorium, tylko bez tych "wzbogaceń" z hugo_memorize*. Mozna sobie zobaczyc dokładniej jak to działa) Napiszę jeszcze info z prośbą, żeby pododawać tę funkcję do swoich funkcji. A i jeżeli ktoś chce dodać coś jeszcze oprócz samego wpisu z wywołaniem funkcji, to można oczywiście zmodyfikować. 
Nie wiem czy to dotyczyło Twojego pytania, ale się wtrąciłem :D 
Maciek Kurek
