### ISSUE TITLE
Failed

### ISSUE THREAD

**Issue by MalgosiaL** [hugo4r/hugo#15]
Widzę, że coś jest nie tak i chcę to naprawić, ale nie wiem, w czym jest problem. Jakby ktoś wiedział jak to cofnąć lub naprawić, to proszę o pomoc.
Małgosia

**Comment by pbiecek** [comment]
W logach na Travis widać, żę jeden błąd jest w przykładach dla hugo_memorise_model
przykłady można opatrzyć blokiem do not run

drugi problem to brak symbolu hugo_history, który nie jest widoczny w środowisku pakietu
takie symbole powinny być poukrywane w .hugoEnv
które jest definiowane tutaj:
https://github.com/hugo4r/hugo/blob/master/R/zzz.R

Zawsze przed commit warto upewnić się, że wysyłany kod nie ma błędów
można to zrobić poleceniem devtools::check()

**Comment by MalgosiaL** [comment]
Z przykładem sobie poradziłam, dziękuję, ale dalszej części nadal nie rozumiem i nie umiem naprawić.
