### ISSUE TITLE
hugo_show_history() - "note" przy wywoływaniu check() 

### ISSUE THREAD

**Issue by AnnaGierlak** [hugo4r/hugo#17]
Funkcja check() nie wskazuje tego jako błąd, ale myślę, że warto na to spojrzeć i poprawić:

checking R code for possible problems ... NOTE
add_to_history: no visible global function definition for 'savehistory'
add_to_history: no visible binding for '<<-' assignment to
  'hugo_history'
add_to_history: no visible binding for global variable 'hugo_history'
hugo_show_history: no visible binding for global variable
  'hugo_history'
Undefined global functions or variables:
  hugo_history savehistory
Consider adding
  importFrom("utils", "savehistory")
to your NAMESPACE file.

**Comment by pbiecek** [comment]
Travis traktuje jako błąd wszystko co nie jest OK
Używanie <<- to bardzo zły pomysł
lepiej wykorzystać środowisko .hugoEnv definiowane w pliku zzz.R

**Comment by lgelmo** [comment]
ok, wydaje mi się, że poprawione
