### ISSUE TITLE
Błędy przy ładowaniu 'rJava'

### ISSUE THREAD

**Issue by monikachudek** [hugo4r/hugo#27]
Po pobraniu aktualnej wersji repozytorium nie mogę nic zrobić, ponieważ:

> Error in (function (dep_name, dep_ver = NA, dep_compare = NA)  : 
>   Dependency package xlsx not available.

wywołanie library(xlsx) powoduje:

> Ładowanie wymaganego pakietu: rJava
> Error: package or namespace load failed for ‘rJava’:
>  .onLoad nie powiodło się w funkcji 'loadNamespace()' dla pakietu 'rJava', szczegóły:
>   wywołanie: inDL(x, as.logical(local), as.logical(now), ...)
>   błąd:  unable to load shared object 'C:/Users/Lenovo/Documents/R/win-library/3.4/rJava/libs/x64/rJava.dll':
>   LoadLibrary failure:  Nie można odnaleźć określonego modułu.

Stack podpowiada 
```
if (Sys.getenv("JAVA_HOME")!="")
+     Sys.setenv(JAVA_HOME="")
> library(rJava)
```
lub 

```
Sys.setenv(JAVA_HOME='C:\\Program Files\\Java\\jre1.8.0_171\\')
library(rJava)
```
Jednak żaden z tych sposobów nie pomaga, czy ktoś potrafi rozwiązać ten problem?

**Comment by komosinskid** [comment]
Wydaje mi się, że po prostu musisz miec zainstalowaną taką normalną javę.

**Comment by monikachudek** [comment]
mam zainstalowana

**Comment by pbiecek** [comment]
zależność od java to proszenie się o problemy na OSX, 
dlatego zaleca się openxlsx do czytania xlsx

**Comment by komosinskid** [comment]
dobra, zmienię

**Comment by komosinskid** [comment]
Nie, jednak nie zmienię, ponieważ openxlsx nie radzi sobie z plikami .xls a tamten pakiet już tak

 Error in read.xlsx.default(path) : 
  openxlsx can not read .xls or .xlm files!

**Comment by kozaka93** [comment]
Mam taki sam problem jak Monika.
@komosinskid  możesz to zmienić, bo nie mogę nic dorzucić na repo?

**Comment by komosinskid** [comment]
Zmienione
