### ISSUE TITLE
Problemy z testowaniem

### ISSUE THREAD

**Issue by AnnaGierlak** [hugo4r/hugo#30]
Czy ktoś z Was miał podczas testowania swojej funkcji komunikaty typu:
Actual message: "cannot open the connection"
cannot open file 'histor.txt': No such file or directory
cannot open the connection

Żadne testy nie chcą mi przejść :(

**Comment by komosinskid** [comment]
usun

add_to_history('hugo_memorise')

bo to jest juz nieaktualne i nie dziala
