### ISSUE TITLE
Usunięcie repozytorium hugo

### ISSUE THREAD

**Issue by komosinskid** [hugo4r/hugo#36]
Chchciałbym usunąć hugo u siebie, co mam je sforkowane. Chciałbym się upewnić, że jak kliknę u siebie w
komosinskid/hugo - settings - delete repository
to usunie się tylko moje a nie przypadkiem też to główne

**Comment by kromash** [comment]
Spokojnie, nie usuniesz głównego :)

**Comment by komosinskid** [comment]
Dzięki xD
